[platformio]
default_envs = zy12pdn

[env:zy12pdn]
platform = ststm32@19.0.0
board = demo_f030f4
framework = libopencm3
platform_packages =
    platformio/toolchain-gccarmnoneeabi@1.70201.0
    platformio/framework-libopencm3@1.10000.260625
    platformio/tool-scons@4.40801.0
build_src_filter = +<main.cpp>
build_flags = -g0 -Wall -Wextra
upload_protocol = cmsis-dap
